site_name: City Dashboard Docs
pages:
- ['index.md', 'Home']
- ['Manual/Creating_a_Dashboard.md', 'Manual']
- ['Dashboard.md', 'Core', 'Dashboard']
- ['CityDashboard.md', 'Core', 'CityDashboard']
- ['Layouts/Layout.md', 'Core', 'Layout']
- ['InfoWindow.md', 'Core', 'InfoWindow']
- ['Maps/GoogleMap.md', 'Core', 'GoogleMap']
- ['Layers/MarkerLayer.md', 'Layers', 'Layer']
- ['Layers/MarkerLayer.md', 'Layers', 'MarkerLayer']
- ['Layers/MarkerLayer.md', 'Layers', 'GridLayer']
- ['Layers/MarkerLayer.md', 'Layers', 'HeatmapLayer']
- ['Layers/Markers/Marker.md', 'Markers', 'Marker']
- ['Layers/Markers/SimpleMarker.md', 'Markers', 'SimpleMarker']
- ['Layers/Markers/ImageMarker.md', 'Markers', 'ImageMarker']
- ['Layers/Markers/CircleMarker.md', 'Markers', 'CircleMarker']
- ['Layers/Markers/PolylineMarker.md', 'Markers', 'PolylineMarker']
- ['Layers/Grids/Grid.md', 'Grids', 'Grid']
- ['Layers/Grids/SquareGrid.md', 'Grids', 'SquareGrid']
- ['Layers/Grids/HexagonalGrid.md', 'Grids', 'HexagonalGrid']
- ['Layers/Heatmaps/Heatmap.md', 'Heatmaps', 'Heatmap']
- ['Visualizations/Visualization.md', 'Visualizations', 'Visualization']
- ['Visualizations/SummaryVisualization.md', 'Visualizations', 'SummaryVisualization']
- ['Visualizations/ChartistVisualization.md', 'Visualizations', 'ChartistVisualization']
- ['lib/utils.md', 'Utils']
theme: readthedocs
