site_name: City Dashboard Docs
pages:
- ['index.md', 'Home']
- ['Manual/Creating_a_Dashboard.md', 'Manual']
- ['Dashboard.md', 'Core', 'Dashboard']
- ['CityDashboard.md', 'Core', 'CityDashboard']
- ['InfoWindow.md', 'Core', 'InfoWindow']
- ['Maps/GoogleMap.md', 'Core', 'GoogleMap']
- ['Layers/Layer.md', 'Layers', 'Layer']
- ['Layers/MarkerLayer.md', 'Layers', 'MarkerLayer']
- ['Layers/GridLayer.md', 'Layers', 'GridLayer']
- ['Layers/HeatmapLayer.md', 'Layers', 'HeatmapLayer']
- ['Layers/LayerSelector.md', 'Layers', 'LayerSelector']
- ['Layers/Markers/Marker.md', 'Markers', 'Marker']
- ['Layers/Markers/SimpleMarker.md', 'Markers', 'SimpleMarker']
- ['Layers/Markers/ImageMarker.md', 'Markers', 'ImageMarker']
- ['Layers/Markers/CircleMarker.md', 'Markers', 'CircleMarker']
- ['Layers/Markers/PolylineMarker.md', 'Markers', 'PolylineMarker']
- ['Layers/Grids/Grid.md', 'Grids', 'Grid']
- ['Layers/Grids/SquareGrid.md', 'Grids', 'SquareGrid']
- ['Layers/Grids/HexagonalGrid.md', 'Grids', 'HexagonalGrid']
- ['Layers/Grids/GridSelector.md', 'Grids', 'GridSelector']
- ['Layers/Heatmaps/Heatmap.md', 'Heatmaps', 'Heatmap']
- ['Layers/Heatmaps/PointHeatmap.md', 'Heatmaps', 'PointHeatmap']
- ['Layers/Heatmaps/SegmentHeatmap.md', 'Heatmaps', 'SegmentHeatmap']
- ['Layers/Heatmaps/HeatmapSelector.md', 'Heatmaps', 'HeatmapSelector']
- ['Layers/DTesselation/DTesselation.md', 'Voronoi/Delaunay', 'DTesselation']
- ['Layers/DTesselation/Voronoi.md', 'Voronoi/Delaunay', 'Voronoi']
- ['Layers/DTesselation/Delaunay.md', 'Voronoi/Delaunay', 'Delaunay']
- ['Layers/DTesselation/DTesselationSelector.md', 'Voronoi/Delaunay', 'DTesselationSelector']
- ['Visualizations/Visualization.md', 'Visualizations', 'Visualization']
- ['Visualizations/SummaryVisualization.md', 'Visualizations', 'SummaryVisualization']
- ['Visualizations/ChartistVisualization.md', 'Visualizations', 'ChartistVisualization']
- ['Utils.md', 'Utils']
theme: readthedocs
